[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
dependencies = [
    "df2gspread",
    "pytube",
    "nltk",
    "trafilatura",
    "ffmpeg-python",
    "git+https://github.com/openai/whisper.git"
]